### ISSUE TITLE
Broken in alpha 4

### ISSUE THREAD

**Issue by tlitookilakin** [BraindeadBZH/datalogue#2]
Initially the plugin would not even load due to script errors. I fixed those and was able to load the plugin, but the UI was nonfunctional. I closed and reopened the project to try and fix it, and the editor now crashes whenever it tries to load the project. Console is full of parse errors and failed script compiles.

**Comment by BraindeadBZH** [comment]
I have a fix for alpha4. It is in the repo. The AssetLib is not on latest version. I test the plugin with any new version.
For the crashes, you light want to delete the .godot folder.

**Comment by tlitookilakin** [comment]
thanks! Will try that.

**Comment by tlitookilakin** [comment]
I'm no longer getting crashes, but Datalogue doesn't work after being installed and enabled until after restarting the editor. I know this was an issue with other addons in 3.0, so hopefully it will get ironed out before then.
